export const workData = [
  {
    id: 1,
    uniqueId: "advertising-design",
    title: "Advertising Design",
    image: "https://i.postimg.cc/fTbGH1HS/Ads-1.jpg",
    link: "link_to_advertising_design_portfolio",
    about: "Creative advertising designs tailored for print and digital media.",
  },
  {
    id: 2,
    uniqueId: "brand-identity-design",
    title: "Brand Identity Design",
    image: "https://i.postimg.cc/Dw9Rw071/Ads-2.jpg",
    link: "link_to_brand_identity_portfolio",
    about:
      "Complete brand identity solutions, including logo, typography, and more.",
  },
  {
    id: 3,
    uniqueId: "typography-design",
    title: "Typography Design",
    image: "https://i.postimg.cc/gJNM82bS/typo-1.jpg",
    link: "link_to_typography_portfolio",
    about: "Custom typography for branding and marketing materials.",
  },
  {
    id: 4,
    uniqueId: "product-designer",
    title: "Product Designer",
    image: "https://i.postimg.cc/h4MF1K0q/Ads-3.jpg",
    link: "link_to_product_design_portfolio",
    about:
      "Unique product design concepts with functionality and aesthetics in mind.",
  },
  {
    id: 5,
    uniqueId: "social-media-graphics",
    title: "Social Media Graphics",
    image: "https://i.postimg.cc/Bb7V9QhL/dont-know.jpg",
    link: "link_to_social_media_graphics_portfolio",
    about: "Engaging social media posts and graphics to boost online presence.",
  },
  {
    id: 6,
    uniqueId: "logo-design",
    title: "Logo Design",
    image: "https://i.postimg.cc/5t8TYJtT/brand-1.jpg",
    link: "https://www.behance.net/gallery/210559285/CodeMegan-Technology",
    about: "Professional logo designs for various brands and industries.",
  },
  {
    id: 7,
    uniqueId: "illustrator",
    title: "Illustrator",
    image: "https://i.postimg.cc/gJNM82bS/typo-1.jpg",
    link: "link_to_illustrator_portfolio",
    about: "Illustrations for books, marketing, and more.",
  },
  {
    id: 8,
    uniqueId: "publication-design",
    title: "Publication Design",
    image: "https://i.postimg.cc/CKCrM4PV/product-design-1.jpg",
    link: "link_to_publication_design_portfolio",
    about: "Designs for magazines, brochures, and other print publications.",
  },
  {
    id: 9,
    uniqueId: "exhibition-designer",
    title: "Exhibition Designer",
    image: "https://i.postimg.cc/yxxLPCVV/typo-2.jpg",
    link: "link_to_exhibition_design_portfolio",
    about: "Creative booth and exhibition stand designs for trade shows.",
  },
  {
    id: 10,
    uniqueId: "packaging-design",
    title: "Packaging Design",
    image: "https://i.postimg.cc/Sx2w4Cby/Ads-4.jpg",
    link: "link_to_packaging_design_portfolio",
    about: "Innovative packaging designs to enhance product appeal.",
  },
  {
    id: 11,
    uniqueId: "letterhead-design",
    title: "Letterhead Design",
    image: "https://i.postimg.cc/0Qf4nCDC/brand-3.jpg",
    link: "link_to_letterhead_design_portfolio",
    about: "Personalized letterhead designs for business communications.",
  },
  {
    id: 12,
    uniqueId: "visiting-card",
    title: "Visiting Card",
    image: "https://i.postimg.cc/jd9FM2wB/illusrtaion-3.jpg",
    link: "link_to_visiting_card_portfolio",
    about: "Elegant visiting card designs for professionals.",
  },
  {
    id: 13,
    uniqueId: "user-interface-design",
    title: "User Interface Design",
    image: "https://i.postimg.cc/rp2YLH9J/illustration-1.jpg",
    link: "link_to_ui_design_portfolio",
    about: "UI designs with a focus on user experience and interaction.",
  },
  {
    id: 14,
    uniqueId: "user-experience-design",
    title: "User Experience Design",
    image: "https://i.postimg.cc/Y9kVQPG9/brand-2.jpg",
    link: "link_to_ux_design_portfolio",
    about: "UX design process including wireframes, prototypes, and research.",
  },
  {
    id: 15,
    uniqueId: "business-card-design",
    title: "Business Card Design",
    image: "https://i.postimg.cc/59sGFnx4/dont-know-2.jpg",
    link: "link_to_business_card_design_portfolio",
    about: "Professional business card designs for branding and marketing.",
  },
  {
    id: 16,
    uniqueId: "brochure-design",
    title: "Brochure Design",
    image: "https://i.postimg.cc/8PsYdM5h/illusration-2.jpg",
    link: "link_to_brochure_design_portfolio",
    about: "Creative brochure designs for businesses and organizations.",
  },
  {
    id: 17,
    uniqueId: "website-1",
    title: "Website 1",
    image: "https://mdbootstrap.com/img/new/standard/nature/111.webp",
    link: "link_to_website1",
    about: "A modern website designed for a healthcare service.",
  },
  {
    id: 18,
    uniqueId: "website-2",
    title: "Website 2",
    image: "https://mdbootstrap.com/img/new/standard/nature/111.webp",
    link: "link_to_website2",
    about: "E-commerce platform with a focus on user-friendly navigation.",
  },
  {
    id: 19,
    uniqueId: "website-3",
    title: "Website 3",
    image: "https://mdbootstrap.com/img/new/standard/nature/111.webp",
    link: "link_to_website3",
    about: "Portfolio website showcasing a creative studio's work.",
  },
  {
    id: 20,
    uniqueId: "website-4",
    title: "Website 4",
    image: "https://mdbootstrap.com/img/new/standard/nature/111.webp",
    link: "link_to_website3",
    about: "Portfolio website showcasing a creative studio's work.",
  },
  {
    id: 21,
    uniqueId: "website-5",
    title: "Website 5",
    image: "https://mdbootstrap.com/img/new/standard/nature/111.webp",
    link: "link_to_website3",
    about: "Portfolio website showcasing a creative studio's work.",
  },
];

export const DetailedWorkData = [
  {
    uniqueId: "advertising-design",
    heading: "Advertising Design",
    description:
      "From a graphic designer's point of view, an advertising design project is an exciting opportunity to blend creativity with strategic thinking. It requires not only artistic skills but also an understanding of marketing principles to create designs that resonate with the target audience. The challenge lies in transforming abstract ideas into tangible visual solutions that drive engagement and conversion.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/111.webp",
      "https://mdbootstrap.com/img/new/standard/nature/112.webp",
      "https://mdbootstrap.com/img/new/standard/nature/113.webp",
      "https://mdbootstrap.com/img/new/standard/nature/114.webp",
      "https://mdbootstrap.com/img/new/standard/nature/115.webp",
    ],
    rating: 4.5,
    tags: ["Digital Advertising", "Print Media", "Creative Design"],
  },
  {
    uniqueId: "brand-identity-design",
    heading: "Brand Identity",
    description:
      "Comprehensive brand identity solutions encompassing logo design, color schemes, typography, and more.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/116.webp",
      "https://mdbootstrap.com/img/new/standard/nature/117.webp",
      "https://mdbootstrap.com/img/new/standard/nature/118.webp",
      "https://mdbootstrap.com/img/new/standard/nature/119.webp",
      "https://mdbootstrap.com/img/new/standard/nature/120.webp",
    ],
    rating: 5,
    tags: ["Branding", "Logo Design", "Typography"],
  },
  {
    uniqueId: "typography-design",
    heading: "Typography Design",
    description:
      "Custom typography solutions for branding, ensuring strong visual appeal and message clarity.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/121.webp",
      "https://mdbootstrap.com/img/new/standard/nature/122.webp",
      "https://mdbootstrap.com/img/new/standard/nature/123.webp",
      "https://mdbootstrap.com/img/new/standard/nature/124.webp",
      "https://mdbootstrap.com/img/new/standard/nature/125.webp",
    ],
    rating: 4.8,
    tags: ["Typography", "Branding", "Marketing"],
  },
  {
    uniqueId: "product-designer",
    heading: "Product Design Innovations",
    description:
      "Creative and functional product design for commercial and industrial needs.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/126.webp",
      "https://mdbootstrap.com/img/new/standard/nature/127.webp",
      "https://mdbootstrap.com/img/new/standard/nature/128.webp",
      "https://mdbootstrap.com/img/new/standard/nature/129.webp",
      "https://mdbootstrap.com/img/new/standard/nature/130.webp",
    ],
    rating: 4.7,
    tags: ["Product Design", "Industrial Design", "Innovation"],
  },
  {
    uniqueId: "social-media-graphics",
    heading: "Social Media Graphics",
    description:
      "Engaging and vibrant graphics to elevate social media presence and campaigns.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/131.webp",
      "https://mdbootstrap.com/img/new/standard/nature/132.webp",
      "https://mdbootstrap.com/img/new/standard/nature/133.webp",
      "https://mdbootstrap.com/img/new/standard/nature/134.webp",
      "https://mdbootstrap.com/img/new/standard/nature/135.webp",
    ],
    rating: 4.9,
    tags: ["Social Media", "Marketing", "Graphics"],
  },
  {
    uniqueId: "logo-design",
    heading: "Logo Design Mastery",
    description:
      "Unique and memorable logos designed to make brands stand out.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/136.webp",
      "https://mdbootstrap.com/img/new/standard/nature/137.webp",
      "https://mdbootstrap.com/img/new/standard/nature/138.webp",
      "https://mdbootstrap.com/img/new/standard/nature/139.webp",
      "https://mdbootstrap.com/img/new/standard/nature/140.webp",
    ],
    rating: 5,
    tags: ["Logo Design", "Branding", "Identity"],
  },
  {
    uniqueId: "illustrator",
    heading: "Illustration Excellence",
    description:
      "Custom illustrations for branding, marketing, and storytelling.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/141.webp",
      "https://mdbootstrap.com/img/new/standard/nature/142.webp",
      "https://mdbootstrap.com/img/new/standard/nature/143.webp",
      "https://mdbootstrap.com/img/new/standard/nature/144.webp",
      "https://mdbootstrap.com/img/new/standard/nature/145.webp",
    ],
    rating: 4.6,
    tags: ["Illustration", "Visual Art", "Creative"],
  },
  {
    uniqueId: "publication-design",
    heading: "Publication Design",
    description:
      "Creative layout and design for brochures, magazines, and other publications.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/146.webp",
      "https://mdbootstrap.com/img/new/standard/nature/147.webp",
      "https://mdbootstrap.com/img/new/standard/nature/148.webp",
      "https://mdbootstrap.com/img/new/standard/nature/149.webp",
      "https://mdbootstrap.com/img/new/standard/nature/150.webp",
    ],
    rating: 4.7,
    tags: ["Publication", "Print Design", "Creative"],
  },
  {
    uniqueId: "exhibition-designer",
    heading: "Exhibition Design",
    description:
      "Custom stand and booth designs to create captivating exhibition experiences.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/151.webp",
      "https://mdbootstrap.com/img/new/standard/nature/152.webp",
      "https://mdbootstrap.com/img/new/standard/nature/153.webp",
      "https://mdbootstrap.com/img/new/standard/nature/154.webp",
      "https://mdbootstrap.com/img/new/standard/nature/155.webp",
    ],
    rating: 4.4,
    tags: ["Exhibition Design", "Trade Shows", "Booth Design"],
  },
  {
    uniqueId: "packaging-design",
    heading: "Packaging Design",
    description:
      "Innovative and eye-catching packaging designs that elevate product appeal.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/156.webp",
      "https://mdbootstrap.com/img/new/standard/nature/157.webp",
      "https://mdbootstrap.com/img/new/standard/nature/158.webp",
      "https://mdbootstrap.com/img/new/standard/nature/159.webp",
      "https://mdbootstrap.com/img/new/standard/nature/160.webp",
    ],
    rating: 4.9,
    tags: ["Packaging", "Design", "Product Presentation"],
  },
  {
    uniqueId: "vehicle-wraps",
    heading: "Vehicle Wraps Design",
    description:
      "Custom vehicle wraps that turn cars and trucks into moving advertisements.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/161.webp",
      "https://mdbootstrap.com/img/new/standard/nature/162.webp",
      "https://mdbootstrap.com/img/new/standard/nature/163.webp",
      "https://mdbootstrap.com/img/new/standard/nature/164.webp",
      "https://mdbootstrap.com/img/new/standard/nature/165.webp",
    ],
    rating: 4.5,
    tags: ["Vehicle Wraps", "Advertising", "Marketing"],
  },
  {
    uniqueId: "letterhead-design",
    heading: "Letterhead Design",
    description:
      "Professional letterhead designs for businesses and individuals.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/166.webp",
      "https://mdbootstrap.com/img/new/standard/nature/167.webp",
      "https://mdbootstrap.com/img/new/standard/nature/168.webp",
      "https://mdbootstrap.com/img/new/standard/nature/169.webp",
      "https://mdbootstrap.com/img/new/standard/nature/170.webp",
    ],
    rating: 4.3,
    tags: ["Letterhead", "Business Stationery", "Branding"],
  },
  {
    uniqueId: "visiting-card",
    heading: "Visiting Card Design",
    description:
      "Elegant and creative visiting card designs for professionals.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/171.webp",
      "https://mdbootstrap.com/img/new/standard/nature/172.webp",
      "https://mdbootstrap.com/img/new/standard/nature/173.webp",
      "https://mdbootstrap.com/img/new/standard/nature/174.webp",
      "https://mdbootstrap.com/img/new/standard/nature/175.webp",
    ],
    rating: 4.9,
    tags: ["Visiting Card", "Stationery", "Business Cards"],
  },
  {
    uniqueId: "user-interface-design",
    heading: "User Interface Design",
    description:
      "Designing modern and functional user interfaces for web and mobile applications.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/176.webp",
      "https://mdbootstrap.com/img/new/standard/nature/177.webp",
      "https://mdbootstrap.com/img/new/standard/nature/178.webp",
      "https://mdbootstrap.com/img/new/standard/nature/179.webp",
      "https://mdbootstrap.com/img/new/standard/nature/180.webp",
    ],
    rating: 5,
    tags: ["UI Design", "Web Design", "Mobile App Design"],
  },
  {
    uniqueId: "web-design-development",
    heading: "Web Design & Development",
    description:
      "Comprehensive web design and development solutions for businesses of all sizes.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/181.webp",
      "https://mdbootstrap.com/img/new/standard/nature/182.webp",
      "https://mdbootstrap.com/img/new/standard/nature/183.webp",
      "https://mdbootstrap.com/img/new/standard/nature/184.webp",
      "https://mdbootstrap.com/img/new/standard/nature/185.webp",
    ],
    rating: 4.8,
    tags: ["Web Design", "Development", "Digital Solutions"],
  },
  {
    uniqueId: "motion-graphics",
    heading: "Motion Graphics",
    description:
      "Dynamic motion graphics and animations for commercials, presentations, and more.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/186.webp",
      "https://mdbootstrap.com/img/new/standard/nature/187.webp",
      "https://mdbootstrap.com/img/new/standard/nature/188.webp",
      "https://mdbootstrap.com/img/new/standard/nature/189.webp",
      "https://mdbootstrap.com/img/new/standard/nature/190.webp",
    ],
    rating: 4.6,
    tags: ["Motion Graphics", "Animation", "Creative"],
  },
  {
    uniqueId: "digital-marketing-campaign",
    heading: "Digital Marketing Campaign",
    description:
      "Comprehensive digital marketing solutions with engaging campaigns across platforms.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/191.webp",
      "https://mdbootstrap.com/img/new/standard/nature/192.webp",
      "https://mdbootstrap.com/img/new/standard/nature/193.webp",
      "https://mdbootstrap.com/img/new/standard/nature/194.webp",
      "https://mdbootstrap.com/img/new/standard/nature/195.webp",
    ],
    rating: 4.8,
    tags: ["Digital Marketing", "SEO", "Social Media"],
  },
  {
    uniqueId: "photography-project",
    heading: "Professional Photography",
    description:
      "High-quality professional photography for events, marketing, and personal projects.",
    images: [
      "https://mdbootstrap.com/img/new/standard/nature/196.webp",
      "https://mdbootstrap.com/img/new/standard/nature/197.webp",
      "https://mdbootstrap.com/img/new/standard/nature/198.webp",
      "https://mdbootstrap.com/img/new/standard/nature/199.webp",
      "https://mdbootstrap.com/img/new/standard/nature/200.webp",
    ],
    rating: 4.9,
    tags: ["Photography", "Visual Art", "Creative"],
  },
];
